# Fly.io app configuration
app = "arbitragexplus-api"

# Docker build (preferred for reliability)
[build]
  dockerfile = "services/api-server/Dockerfile"

# Environment variables exposed at runtime
[env]
  NODE_ENV = "production"
  PORT = "3000"

# HTTP service configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.healthcheck]
    path = "/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
