# Fly.io app configuration
app = "arbitragexplus-api"
primary_region = "mia"

# Docker build (preferred for reliability)
[build]
  dockerfile = "services/api-server/Dockerfile"

# Environment variables exposed at runtime
[env]
  NODE_ENV = "production"
  PORT = "3000"

# HTTP service configuration
[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"

# VM configuration
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
