[app]
  name = "arbitragexplus-frontend"
  primary_region = "scl"
  
[build]
  builder = "paketobuildpacks/builder-jammy-base"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 3

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

