[package]
name = "rust-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-core = { path = "../rust-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.7"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "engine-http"
path = "src/main.rs"
