# Configuración de Monitoreo - ARBITRAGEXPLUS2025
# Actualizado: 2025-10-17

health_checks:
  enabled: true
  interval: 30
  timeout: 5
  
  # URLs configurables por entorno
  # Usar variables de entorno en producción con HTTPS
  endpoints:
    api_server:
      url: "${API_SERVER_URL:-http://localhost:3000}/health"
      critical: true
      # NOTA: HTTP solo para desarrollo local
      allow_insecure_localhost: true
    
    python_collector:
      url: "${PYTHON_COLLECTOR_URL:-http://localhost:8000}/health"
      critical: true
      allow_insecure_localhost: true
    
    rust_engine:
      url: "${RUST_ENGINE_URL:-http://localhost:8080}/health"
      critical: false
      allow_insecure_localhost: true

monitoring:
  metrics:
    enabled: true
    port: 9090
  
  logging:
    level: "${LOG_LEVEL:-info}"
    format: "json"
  
  alerts:
    enabled: true
    channels:
      - type: "webhook"
        url: "${ALERT_WEBHOOK_URL}"
