# Configuración de Estrategias de Arbitraje
# Estrategias dinámicas cargadas desde Google Sheets
# Hoja: ROUTES (200 campos)

# Estrategias habilitadas
enabled_strategies:
  - two_dex_arbitrage
  - three_dex_arbitrage
  - flash_loan_arbitrage
  - cross_chain_arbitrage

# Configuración de Two-DEX Arbitrage
two_dex_arbitrage:
  enabled: true
  min_profit_usd: 10
  min_profit_percent: 0.5
  max_gas_price_gwei: 50
  max_slippage_percent: 1.0
  execution_timeout_seconds: 30
  
  # Pares de DEXs preferidos
  preferred_dex_pairs:
    - [uniswap_v3, sushiswap]
    - [uniswap_v3, pancakeswap]
    - [sushiswap, balancer]

# Configuración de Three-DEX Arbitrage
three_dex_arbitrage:
  enabled: true
  min_profit_usd: 15
  min_profit_percent: 0.75
  max_gas_price_gwei: 45
  max_slippage_percent: 1.5
  execution_timeout_seconds: 45
  
  # Rutas triangulares preferidas
  preferred_routes:
    - [uniswap_v3, sushiswap, balancer]
    - [pancakeswap, curve, uniswap_v3]

# Configuración de Flash Loan Arbitrage
flash_loan_arbitrage:
  enabled: true
  min_profit_usd: 20
  min_profit_percent: 1.0
  max_gas_price_gwei: 60
  max_slippage_percent: 2.0
  execution_timeout_seconds: 60
  
  # Proveedores de flash loans
  flash_loan_providers:
    aave_v3:
      enabled: true
      fee_percent: 0.09
      max_loan_usd: 1000000
    
    balancer:
      enabled: true
      fee_percent: 0.0
      max_loan_usd: 500000
    
    uniswap_v3:
      enabled: true
      fee_percent: 0.0
      max_loan_usd: 750000

# Configuración de Cross-Chain Arbitrage
cross_chain_arbitrage:
  enabled: false  # Requiere bridges configurados
  min_profit_usd: 50
  min_profit_percent: 2.0
  max_bridge_time_seconds: 600
  
  # Bridges soportados
  supported_bridges:
    - stargate
    - hop_protocol
    - across

# Configuración de Optimización
optimization:
  algorithm: "dynamic_programming"
  max_routes_to_evaluate: 1000
  max_computation_time_ms: 500
  parallel_evaluation: true
  max_parallel_workers: 8
  
  # Ranking de rutas
  ranking_weights:
    profit_usd: 0.4
    profit_percent: 0.3
    gas_cost: 0.2
    execution_time: 0.1

# Configuración de Riesgo
risk_management:
  max_position_size_usd: 100000
  max_daily_loss_usd: 5000
  max_consecutive_failures: 3
  
  # Circuit breakers
  circuit_breakers:
    enabled: true
    trigger_on_loss_percent: 5.0
    cooldown_seconds: 300
    auto_resume: true

# Configuración de Ejecución
execution:
  dry_run_mode: false
  simulate_before_execute: true
  require_oracle_validation: true
  max_retries: 2
  retry_delay_seconds: 5
  
  # Validación pre-ejecución
  pre_execution_checks:
    - check_pool_liquidity
    - check_gas_price
    - check_oracle_prices
    - check_slippage_tolerance
    - check_profit_threshold

# Configuración de Monitoreo
monitoring:
  log_all_opportunities: true
  log_execution_details: true
  track_performance_metrics: true
  alert_on_failures: true
  alert_on_low_profitability: true
  
  # Métricas a trackear
  metrics:
    - total_opportunities_detected
    - total_opportunities_executed
    - total_profit_usd
    - average_profit_percent
    - success_rate
    - average_execution_time
    - gas_costs_total

